# Generated by Django 4.1.5 on 2023-01-18 09:40

from django.db import migrations
from users.models import User


def add_admin(*args, **kwargs):  # noqa
    User.objects.create_superuser(email='admin@admin.admin', password='admin')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_admin)
    ]
