# Generated by Django 4.1.5 on 2023-01-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_discount',
            field=models.IntegerField(default=0),
        ),
    ]
