version: "3.7"

services:

  db:
    container_name: db
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_NAME: bookstore
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: bookstore
      POSTGRES_PORT: 5432

  bookstore:
    container_name: bookstore
    build: .
    command: bash entrypoint.sh
    platform: linux/amd64
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    env_file:
      .env
    depends_on:
      - db

volumes:
  pg_data: {}
