# Generated by Django 4.1.5 on 2023-01-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='quantity',
            new_name='in_stock',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
