# Generated by Django 4.1.5 on 2023-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
