# Generated by Django 4.1.5 on 2023-06-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='address',
            field=models.CharField(max_length=250, null=True, verbose_name='Delivery address'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Delivery city'),
        ),
    ]
