# Generated by Django 4.1.5 on 2023-01-16 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to='books.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.fields.NOT_PROVIDED, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
