# Generated by Django 4.1.5 on 2023-06-22 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('favorites', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
