# Generated by Django 4.1.5 on 2023-01-17 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_quantity_book_in_stock_delete_cart'),
        ('favorites', '0002_alter_favorite_book_id_alter_favorite_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='book_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
