# Generated by Django 4.1.5 on 2023-01-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name="Genre's title")),
                ('description', models.CharField(max_length=400, verbose_name="Genre's description")),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
            ],
        ),
    ]
