# Generated by Django 4.1.5 on 2023-01-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name="Genre's title"),
        ),
    ]
